### ISSUE TITLE
No activity on launcing the executable.

### ISSUE THREAD

**Issue by vaibhav1307** [shaw4/tidal-rpc#1]
Amazing work on tidal rpc man. but for some reasons it is opens a blank terminal on launching the executable .

**Comment by vars1ty** [comment]
Thanks for reporting this!
I'll take a look at it

**Comment by vars1ty** [comment]
Fixed 👍
You can grab the latest version from `~/bin/Debug/net5.0`

**Comment by vaibhav1307** [comment]
idk why man but the issue still persists.. Am i missing something to do ..like editing any config file.?? the executable just opens and closes instantly :(
